
POST http://localhost:8081/users HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2ZTJjYWNlLTkxNjQtNDY3OC04YzYzLTJhMTdhOGI4YjgwNiIsInVzZXJuYW1lIjoiYWRtaW4xQHRlc3RlLmNvbSIsInByb2ZpbGUiOiJBRE1JTiIsImNvbXBhbnkiOm51bGwsImlhdCI6MTY5NDY1MjUwMiwiZXhwIjoxNjk0NjU2MTAyfQ.4PvRTNNuNUq7rpZ5QfT5ziTO1HGuIaxDMhGt9odspJ0


# ADMIN
# {
#     "name": "Admin First",
#     "username": "admin1@teste.com",
#     "password": "senha1234",
#     "profile": "ADMIN"
# }

# RECRUTADOR
# {
#     "name": "Recrutador 1",
#     "username": "recrutador@growdev.com.br",
#     "password": "123456",
#     "profile": "RECRUITER",
#     "company": "Growdev"
# }

