
GET http://localhost:8081/users?profile=ADMIN HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2ZTJjYWNlLTkxNjQtNDY3OC04YzYzLTJhMTdhOGI4YjgwNiIsInVzZXJuYW1lIjoiYWRtaW4xQHRlc3RlLmNvbSIsInByb2ZpbGUiOiJBRE1JTiIsImNvbXBhbnkiOm51bGwsImlhdCI6MTY5NDY0NzQ1MiwiZXhwIjoxNjk0NjUxMDUyfQ.oK1vLFlqq657P7SO7cjXVQq3SQc8GQYzQoqKWuzn20o
