
POST http://localhost:8081/jobs HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0MjM3ZmFjLThjMjctNDEyYS1iMWM3LTYzZGYzZjUxZGI5ZSIsInVzZXJuYW1lIjoicmVjcnV0YWRvckBncm93ZGV2LmNvbS5iciIsInByb2ZpbGUiOiJSRUNSVUlURVIiLCJjb21wYW55IjoiR3Jvd2RldiIsImlhdCI6MTY5NDY5MDg0NywiZXhwIjoxNjk0Njk0NDQ3fQ.XmQSPTj4b4LI-2hPHxgnpftMeSlSZvxtVGU7jn2xWF0

{
    "description": "Dev Pleno Full Stack",
    "companyName": "Growdev",
    "isOpen": true,
    "limitDate": "25/09/2023",
    "maxCandidate": 10
}
